export { detectEnvironment, resolveConfig } from './environment.js'
export type { Environment, LocalConfig, ResolvedConfig, SandboxConfig } from './environment.js'
export { GatewayClient } from './gateway-client.js'
export type { GatewayMessage, PresignOperation, PresignedUrl, RemoteFile } from './gateway-client.js'
export { createGatewayLlmProvider } from './gateway-llm-adapter.js'
